server:
  port: 8080

credentials:
  admin:
    name: admin
    password: admin

spring:
  profiles.active: dev

  datasource:
    platform: h2
    url: jdbc:h2:./h2/pf;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled=true:

  jpa:
    open-in-view: false
    ddl-auto: validate

    hibernate:
      use-new-id-generator-mappings: false

    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        temp:
          use_jdbc_metadata_defaults: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-root.xml

  resources:
    cache:
      cachecontrol:
        cache-public: true
      period: 3600

  output:
    ansi:
      enabled: ALWAYS

---
spring:
  profiles: dev
logging:
  file:
    name: logs/dev-app.log
  level:
    org.springframework.web: DEBUG
    ru.pf.controller : DEBUG
    org.hibernate: DEBUG

---
spring:
  profiles: production
logging:
  file:
    name: logs/production-app.log
  level:
    org.springframework.web: WARN
    ru.pf.controller : WARN
    org.hibernate: WARN